### ISSUE TITLE
The error issue

### ISSUE THREAD

**Issue by ilyas-cyber** [RevoltSecurities/ShodanX#8] opened 2024-05-09 17:21 UTC
or: Got unexpected extra argument (eportal.oauife.edu.ng)
shodanx domain eportal.oauife.edu.ng

Usage: shodanx domain [OPTIONS]

Error: Got unexpected extra argument (eportal.oauife.edu.ng)

Usage: shodanx [OPTIONS] COMMAND [ARGS]...

Error: No such option: -d

**Comment by RevoltSecurities** [comment] 2024-05-09 17:47
Hey @ilyas-cyber ,
Please use the command: `shodanx domain --help` to see the help menu because you are passing wrong command for shodanX

Kind regards,
@RevoltSecurities

**Comment by ilyas-cyber** [comment] 2024-05-09 18:11
I have tried this help command can you please give me the right command
that show me the ips of the given targets

Thanks
ilyas

**Comment by ilyas-cyber** [comment] 2024-05-09 18:22
Ok, thank you.

**Comment by ilyas-cyber** [comment] 2024-05-09 18:24
Is there any other tool you use for finding origin ips except : shodan ,
census
Thanks again
ilyas

**Comment by RevoltSecurities** [comment] 2024-05-09 18:33
Hi @ilyas-cyber ,
I hope the issue is completed and Im closing it now and we use many resources than shodan that will be coming as a new tool ASAP. 

kind regards,
@RevoltSecurities

**Comment by ilyas-cyber** [comment] 2024-05-09 19:17
Thanks
Best
ilyas

**Comment by CyberWorld121220** [comment] 2024-05-11 14:43
error code show pls help me
└─$ shodanx domain -d xxxx.xxxx.com -fct ip
[INFO]: Import Error occured in Module imports due to: No module named 'alive_progress'
[INFO]: If you are encountering this issue more than a time please report the issues in ShodanX Github page..

**Comment by RevoltSecurities** [comment] 2024-05-11 15:00
Hi @CyberWorld121220 , 
Thanks you for providing your issue and I required to please use this command:

```code
pip install alive_progress
```

Kind regards,
@RevoltSecurities

**Comment by CyberWorld121220** [comment] 2024-05-11 15:31
Hi @RevoltSecurities

Great, thanks for sharing

**Closed** 2024-05-11 17:08 UTC
Labels: invalid
